
spring:
  mail:
    host: ${MAIL_HOST}
    post: ${MAIL_POST}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    port: ${RABBITMQ_PORT}
  security:
    filter:
      order: -100
    jwt:
      key: ${SECURITY_KEY}
      expire: 1
  data:
    redis:
      database: 0
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
      timeout: 60000
  jackson:
    time-zone: "Asia/Taipei"

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}

  profiles:
    active: prod

avatarImageFilePath: E:\\my-project\\my-project-backend\\src\\main\\resources\\static\\image\\userAvatar\\
