
spring:
  mail:
    host: smtp.gmail.com
    post: 587
    username: 111504one@gmail.com
    password: zehckajnmrhlkakc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 1

  datasource:
    url: jdbc:mysql://localhost:3306/test?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

avatarImageFilePath:  E:\my-project\my-project-backend\src\main\resources\static\image\userAvatar\
